sudo: false
language: node_js
node_js:
- node
os:
- linux
cache:
  yarn: true
  directories:
    - node_modules
addons:
  apt:
    packages:
    - gperf
    - libboost-dev
    - libboost-all-dev
    - libftdi-dev
    - libqt5opengl5
    - python3.5
    - python3.5-dev
    - qt5-default
script:
- yarn build
before_deploy:
- ARCHIVE_NAME="${TRAVIS_TAG:-latest}-$TRAVIS_OS_NAME-`uname -m`.tar"
- DIST_DIR="$TRAVIS_BUILD_DIR/dist"
- echo "ARCHIVE_NAME=$ARCHIVE_NAME DIST_DIR=$DIST_DIR"
- tar --create --verbose --file="$ARCHIVE_NAME" --directory "$TRAVIS_BUILD_DIR/dist" .
deploy:
  provider: releases
  draft: false
  prerelease: true
  file: "$ARCHIVE_NAME"
  skip_cleanup: true
  on:
    tags: true
    node: node
  api_key:
    secure: AlX0G7h9F1Th3jFkv9IDoy1jCuEVWy0/qM6C5S/S6q8eL4OIBFcykEG2bGL7eSTWhPqlbrpgsK8jBiHIfq+7iPfHe+uH6JIxHmq2EI9AiD6XkjqtIHFqI5XcMeobvVLDfvW025VGdNIBWBmgYNDV0h7NZrIYcVVsCG3pUSrOS2EVjHcSTDQEJS3W+8Cw9IimiQEDCRHWmj8bEh7l+byq8gz0B+YD88SkPpnPRvtBd1DbuAy5pko4ydxYIF5XakK+krTc/LGbChpNlzRm4MRSUu3yQhqn0Sk2Ymllm01TJ047VHm1l72I+Iirb64obiDTrhAZrmSdAnsX4ioGY2c6hCO34R+cf6k3KpOgkj+B1KPGHf9cppqD8rc7PUuHiNiyBy6MHBwj/ycI//5CX8QkMltxG64OjbVE7q9kEkOcQteRHaJsBmMNZ46U/Vaa0rFUtlXQk8lnPfE5TQ2JP/TKtkwdUAnIv/KEFMRWSW50GliIwUxC2iWXyqZzpLFwi6ZvM+s/vEczkIlznDAW6dcLVJm7OMCkgEIHw44cpPQlf/euPQ5LlCq8vk+fzmeCpyUAeHrquyLgEJOhVxcJsIdDWSdBA3DfSorLuHAdO6bj98LnaL9jZCFU1xjJCYSdXSLL0ST6/GZAMNsqfaKpsElEfUDfREYqfMAl8hds1UUN+Ss=
